FROM openjdk:8-jdk-alpine
EXPOSE 8080
ARG JAR_FILE=target/docker-jenkins-integration-sample.jar
ADD ${JAR_FILE} docker-jenkins-integration-sample.jar
ENTRYPOINT ["java","-jar","/docker-jenkins-integration-sample.jar"]